### ISSUE TITLE
Add link to deployed gh page into "about" section of repo

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/energy#28]

**Comment by jschirrmacher** [comment]
I would do that but am unable due to a lack of permissions

**Comment by mrsimpson** [comment]
Don't know how to do either of it: find the about section nor how to increase your permissions 😬

**Comment by jschirrmacher** [comment]
Normally, the "about" section should have a icon in to upper right to edit the details like in this screenshot:

<img width="448" alt="Bildschirmfoto 2022-11-15 um 08 51 13" src="https://user-images.githubusercontent.com/2821879/201860593-0823f0c3-1f59-470e-ba84-c9cf4e3468d8.png">

**Comment by mrsimpson** [comment]
Ah, didn't know that one. Done

**Comment by jschirrmacher** [comment]
The link needs to be updated now with the CNAME in action.
Could you please, @mrsimpson ? I'm still not able to do so myself.

**Comment by mrsimpson** [comment]
Done.
I added you as collaborator, but I fear unless we have an organization for that, I can't grant you more permissions...
