### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/energy#43]
we should have something like a navigation in order to enable things like #35

**Comment by mrsimpson** [comment]
The cc was not a call to action ;-)

**Comment by mrsimpson** [comment]
Did you see #44, @jschirrmacher

**Comment by jschirrmacher** [comment]
Oh, actually not. Thanks for the hint

**Comment by mrsimpson** [comment]
Did you do something on that already?

**Comment by jschirrmacher** [comment]
Yes, but I've dropped that already, it was not too much.

**Comment by mrsimpson** [comment]
Fixed with #44
