### ISSUE TITLE
Improve bar charts

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/energy#46]
The bar charts could be a little easier to read if 2023 would have to separate bars: one containing only the gas price and the subsidization (just like 2022), and another one containing same data with the own savings incorporated. It would better illustrate the effect of the savings, and especially how it would affect the own costs and the subsidization.

WDYT @mrsimpson ?

**Comment by mrsimpson** [comment]
Sounds like an idea worth trying out

**Comment by mrsimpson** [comment]
wdyt, @jschirrmacher – is that what you thought?

**Comment by jschirrmacher** [comment]
Very close.

I would recommend to add "mit Einsparung" to the right most bar like the other for 2023 to make that even more clear. 

<img width="809" alt="Bildschirmfoto 2022-11-17 um 21 30 58" src="https://user-images.githubusercontent.com/2821879/202553411-5a8eb764-2abd-44d4-8d9f-c1964219296f.png">
Since the saving is initially zero now, we could also hide the fourth bar in this case and only show it if the user has entered some savings amount.

One thing seems strange to me: if I enter a saving of e.g. 2000kWh, the subsidization is exactly the same in both 2023's bars. Shouldn't it be different due to the limitation of the price that normally would have been to pay? If I use less gas, there should be less money to pay and the subsidization should cover only the amount, that exceeds the 12 cent per kWh I think.

**Comment by mrsimpson** [comment]
WRT hiding the col and renaming it: sounds good, feel free to – I have to sleep tonight.

**Comment by mrsimpson** [comment]
WRT the calculation: the payment you receive in 2023 is a one time payment which is calculated "the difference in price of 0.12 and market price, applied to 80% of the consumption => if you reduce not more than 20%, the subsidization is always the same. Only if you reduce it more, it will be limited to what you effectively consume (less than 80%). 
I do hope I got that right.

**Comment by jschirrmacher** [comment]
WRT the calculation: you're right, it is more difficult to calculate than I expected. But in fact, it sounds reasonable to have an incentive to reduce the consumption to more than 20%.

Maybe we could think about explaining that a little more in the app - at least for the interested.
