### ISSUE TITLE
Explanation components

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/energy#47]
Adding explanations with the necessary long texts may break the layout. 
![image](https://user-images.githubusercontent.com/17176678/202276404-23209400-e63b-4ae0-bffc-adeb12e169f7.png)
A simple Info-icon with a tooltip as a component could help (`NIcon` & `NTooltip`)

**Comment by jschirrmacher** [comment]
Too bad, I've fixed that as well, and get conflicts now. This was what I wanted to express with self-assiging to this issue.

**Comment by jschirrmacher** [comment]
I'll try to merge the two solutions into one, because I've also some more responsiveness issues.
But I will create another PR for that.

**Comment by mrsimpson** [comment]
Ouch. Did not see you already self-assigned it. Just use your solution.

**Comment by mrsimpson** [comment]
I just had ten minutes while my wife was on the phone, thus forgot to self-assign it ;-)
Yours will probably not be directly pushed to master and have a green pipeline and maybe even tests 😬
