### ISSUE TITLE
Warnings from plugin-vue when it tries to resolve xml tags

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/energy#56]
[@vite/plugin-vue](https://github.com/vitejs/vite/tree/main/packages/plugin-vue#readme) tries to resolve the xml+svg paragraph icon as vue template tags. This obviously fails and creates warnings in the dev console of the browser.

I already tried to configure the plugin-vue to exclude xml files but to no avail. Now, I don't have any idea, how to resolve that.

Actually, the implementation of the menu doesn't really looks like how vue components should be implemented IMO. How about using simple `<router-link>`s with an icon instead of the menu? We don't currently need the features of the `<n-menu>`, and I think it will never be necessary.

**Comment by mrsimpson** [comment]
Id not swap the menu on the top (as it works well and looks good), but in the footer, simple router links are probably sufficient. 
I'd just not ~waste~ invest any energy into  non-functional stuff (aka "quality") at the moment ;-)

**Comment by jschirrmacher** [comment]
Agreed.
We could also have a look at [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader). That would simplify things a lot.

**Comment by jschirrmacher** [comment]
I've updated the footer with #71 - I think we should close this ticket now
