### ISSUE TITLE
Proposals for savings

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/energy#8]
As a user, I want so select from some saving proposals, which will be taken into account for 2023

**Comment by mrsimpson** [comment]
Proposal: Simple calculator-icon next to the reduction.
This could bring of an overlay with proposals from which the user can select. This total would then be copied to the targeted reductions

**Comment by jschirrmacher** [comment]
Proposals should be as specific as possible, but could include links to further information for those who want to learn.

- halb so viel duschen (schwierig zu berechnen, da der Gasverbrauch für Warmwasser nicht separat gemessen wird und von vielen Faktoren abhängig ist. Ich habe ein paar [Basisinfos dazu](https://www.energiesparen-im-haushalt.de/energie/bauen-und-modernisieren/modernisierung-haus/heizung-modernisieren/heizungsanlage-erneuern/gasheizung-erneuern/gasverbrauch-warmwasser.html) gefunden.
- den Herd für das Nudelwasser [nach 2min kochen ausschalten](https://www.barilla.com/de-at/passives-kochen) (hilft natürlich nur bei Gasherden)
- Raumtemperatur um 1° reduzieren [spart laut UBA ca. 6%](https://www.umweltbundesamt.de/umwelttipps-fuer-den-alltag/heizen-bauen/heizen-raumtemperatur#gewusst-wie) (oder auch 2° oder 3°, je nach dem, wo man startet)

**Comment by jschirrmacher** [comment]
A first informational dialog exists now (#58), but we should add functionality to let user choose some of the recommendations and add data to automatically increase the amount of savings.

**Comment by mrsimpson** [comment]
@jschirrmacher the dialog looks like a good start 👍 
WDYT about adding a slider to the bottom "based on the above, I plan to reduce my consumption by x%"
On close, this could be copied to the reductions

**Comment by jschirrmacher** [comment]
Sounds great!

**Comment by mrsimpson** [comment]
At least like a very feasible one :)

Maybe we could also just link https://www.energiewechsel.de/KAENEF/Navigation/DE/Thema/energiespartipps.html as "Noch mehr Ideen zum Sparen"

**Comment by jschirrmacher** [comment]
I've added the slider and the additional recommendation now (see #63 and #64).

We could convert the modal to an own menu item. 

We might then ask users to enter some information about housing, how old the house is, if they use gas for cooking etc., or some preferences (e.g. "how often do you take showers currently?"). With that, recommendations could be filtered and savings calculations could be a little more accurate.

**Comment by jschirrmacher** [comment]
The issue gets more and more like an epic...

**Comment by mrsimpson** [comment]
I do think the current implementation is good enough for this issue.
<img width="488" alt="Bildschirm­foto 2022-11-21 um 09 46 21" src="https://user-images.githubusercontent.com/17176678/203005744-51c58c18-89b8-49b8-97fe-b663dc1e5d0a.png">

WDYT about closing this issue and create a new one for a savings-model (the stuff you started in `settings`)
<img width="1032" alt="Bildschirm­foto 2022-11-21 um 09 49 20" src="https://user-images.githubusercontent.com/17176678/203006072-eadc8440-c023-4f20-910b-8df7f2e42012.png">

**Comment by jschirrmacher** [comment]
Agreed.
