### ISSUE TITLE
Footer not spanning the full width

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/energy#84]
It's aligned left. I am a CSS legasthenic...
@jschirrmacher you revamped the footer ;-)

**Comment by jschirrmacher** [comment]
Problem comes from https://github.com/mrsimpson/energy/commit/8b408e40d2ea4e568b7c3051f10ec110b4edd970.

The `left: 0; right: 0;` as it was before made it span the whole window width. Now it uses only what it really needs.

We should revert that and use `justify-content: center` for `.menu-bar` instead. I'll create a PR for that

**Comment by mrsimpson** [comment]
Oooops. Did I tell you I'm a css legastehnic? 😬
The `0` made it align left
